const mockJobsData = [
  {
    jobId: "id1",
    title: "JavaScript Developer",
    experience: "1-2 years",
    location: "Bangalore",
    salary: "12-15 lacs",
    skills: ["JavaScript", "Webpack", "jQuery", "Web", "Browser"],
    rolesAndResponsibilities: [
      "Develop web applications using JavaScript and related technologies.",
      "Optimize and debug existing code to improve performance.",
      "Collaborate with UI/UX designers to implement responsive and user-friendly interfaces.",
      "Stay updated with the latest web development trends and technologies.",
    ],
    jobDescription:
      "We are seeking a JavaScript Developer to join our team and contribute to the development of web applications. The ideal candidate should have a solid understanding of JavaScript and related technologies. You will be responsible for optimizing and debugging code, collaborating with designers to create user-friendly interfaces, and staying up to date with the latest web development trends. Join us to work on exciting projects and make a significant impact in the web development field.",
    company: "ABC Tech Solutions",
    contactEmail: "jobs@abc-tech.com",
    deadline: "2023-12-31",
  },
  {
    jobId: "id2",
    title: "Java Developer",
    experience: "1-2 years",
    location: "Bangalore",
    salary: "12-15 lacs",
    skills: ["Java", "Spring", "Hibernate", "SQL"],
    rolesAndResponsibilities: [
      "Design, code, and test high-quality Java applications.",
      "Work with relational databases, write SQL queries, and optimize data access.",
      "Collaborate with cross-functional teams to gather and refine software requirements.",
      "Contribute to the entire software development lifecycle from planning to deployment.",
    ],
    jobDescription:
      "We are looking for a Java Developer to join our software development team. As a Java Developer, you will be responsible for designing, coding, and testing high-quality Java applications. You should have experience with relational databases and the ability to write efficient SQL queries. You will work closely with cross-functional teams to gather and refine software requirements and contribute to the entire software development lifecycle. Join us in delivering innovative software solutions.",
    company: "XYZ Software",
    contactEmail: "hr@xyzsoftware.com",
    deadline: "2023-12-15",
  },
  {
    jobId: "id3",
    title: "Python Developer",
    experience: "1-2 years",
    location: "Bangalore",
    salary: "12-15 lacs",
    skills: ["Python", "Django", "Flask", "SQL"],
    rolesAndResponsibilities: [
      "Develop and maintain Python applications using Django and Flask frameworks.",
      "Design and implement RESTful APIs for web services.",
      "Collaborate with data scientists on data preprocessing and analysis tasks.",
      "Troubleshoot and resolve software defects and issues.",
    ],
    jobDescription:
      "We are looking for a Python Developer to join our team. The ideal candidate will develop and maintain Python applications using Django and Flask frameworks. You will be responsible for designing and implementing RESTful APIs for web services. Additionally, you will collaborate with data scientists on data preprocessing and analysis tasks and troubleshoot and resolve software defects and issues. Join us to work on exciting Python projects.",
    company: "PQR Innovations",
    contactEmail: "careers@pqrinnovations.com",
    deadline: "2023-11-30",
  },
  {
    jobId: "id4",
    title: "Software Developer",
    experience: "1-2 years",
    location: "Bangalore",
    salary: "12-15 lacs",
    skills: ["C#", ".NET", "ASP.NET", "MVC", "SQL"],
    rolesAndResponsibilities: [
      "Develop and maintain software applications using the .NET framework.",
      "Collaborate with software architects to design scalable and efficient solutions.",
      "Write and optimize SQL queries for data retrieval and manipulation.",
      "Participate in code reviews and provide constructive feedback to team members.",
    ],
    jobDescription:
      "We are seeking a Software Developer to join our team. As a Software Developer, you will be responsible for developing and maintaining software applications using the .NET framework. You will collaborate with software architects to design scalable and efficient solutions and work with SQL databases to write and optimize SQL queries. Additionally, you will participate in code reviews and provide constructive feedback to team members. Join us to work on innovative software projects.",
    company: "TechSolutions Inc.",
    contactEmail: "hr@techsolutionsinc.com",
    deadline: "2023-11-20",
  },
  {
    jobId: "id5",
    title: "Lead Developer",
    experience: "5+ years",
    location: "Bangalore",
    salary: "20-25 lacs",
    skills: ["JavaScript", "React", "Node.js", "Team Leadership"],
    rolesAndResponsibilities: [
      "Lead development projects and manage a team of developers.",
      "Architect and develop web applications using modern web technologies.",
      "Mentor junior developers and provide technical guidance.",
      "Collaborate with stakeholders to define project requirements and milestones.",
    ],
    jobDescription:
      "We are looking for a highly experienced Lead Developer to lead our development projects. As a Lead Developer, you will manage a team of developers and play a crucial role in architecting and developing web applications using modern web technologies. You will also mentor junior developers, provide technical guidance, and collaborate with stakeholders to define project requirements and milestones. Join us to lead innovative development projects and make a significant impact.",
    company: "InnovateTech Solutions",
    contactEmail: "careers@innovatetech.com",
    deadline: "2023-11-15",
  },
  {
    jobId: "id6",
    title: "AI/ML Developer",
    experience: "3-5 years",
    location: "Bangalore",
    salary: "18-22 lacs",
    skills: ["Python", "TensorFlow", "Machine Learning", "Deep Learning"],
    rolesAndResponsibilities: [
      "Develop and deploy AI/ML models for various applications.",
      "Collaborate with data scientists to preprocess and analyze large datasets.",
      "Research and implement state-of-the-art machine learning algorithms.",
      "Optimize models for performance and scalability.",
    ],
    jobDescription:
      "We are seeking an AI/ML Developer to join our AI team. The ideal candidate will be responsible for developing and deploying AI/ML models for various applications. You will collaborate with data scientists to preprocess and analyze large datasets and research and implement state-of-the-art machine learning algorithms. Additionally, you will optimize models for performance and scalability. Join us to work on cutting-edge AI/ML projects.",
    company: "AI Innovations",
    contactEmail: "jobs@aiinnovations.com",
    deadline: "2023-11-30",
  },
  {
    jobId: "id7",
    title: "MERN Developer",
    experience: "2-3 years",
    location: "Bangalore",
    salary: "15-18 lacs",
    skills: ["MongoDB", "Express", "React", "Node.js"],
    rolesAndResponsibilities: [
      "Develop web applications using the MERN stack.",
      "Design and implement RESTful APIs with Express and Node.js.",
      "Work with NoSQL databases like MongoDB for data storage.",
      "Collaborate with front-end developers to integrate user interfaces.",
    ],
    jobDescription:
      "We are looking for a MERN Developer to join our development team. As a MERN Developer, you will be responsible for developing web applications using the MERN stack. You will design and implement RESTful APIs with Express and Node.js and work with NoSQL databases like MongoDB for data storage. Additionally, you will collaborate with front-end developers to integrate user interfaces. Join us to work on exciting web development projects.",
    company: "MERN Innovations",
    contactEmail: "hr@merninnovations.com",
    deadline: "2023-12-10",
  },
  {
    jobId: "id8",
    title: "Full Stack Developer",
    experience: "2-3 years",
    location: "Bangalore",
    salary: "15-18 lacs",
    skills: ["JavaScript", "React", "Node.js", "SQL", "Front-end", "Back-end"],
    rolesAndResponsibilities: [
      "Work on both front-end and back-end development of web applications.",
      "Collaborate with UI/UX designers to create visually appealing interfaces.",
      "Design and implement database schemas and write SQL queries.",
      "Participate in code reviews and provide feedback for code improvements.",
    ],
    jobDescription:
      "We are seeking a Full Stack Developer to join our development team. The ideal candidate will work on both front-end and back-end development of web applications. You will collaborate with UI/UX designers to create visually appealing interfaces and design and implement database schemas, writing SQL queries. Additionally, you will participate in code reviews and provide feedback for code improvements. Join us to work on innovative web development projects.",
    company: "FullStack Tech Solutions",
    contactEmail: "careers@fullstacktech.com",
    deadline: "2023-12-05",
  },
  {
    jobId: "id9",
    title: "HR",
    experience: "1-2 years",
    location: "Bangalore",
    salary: "12-15 lacs",
    skills: ["Recruitment", "HR Management", "Communication"],
    rolesAndResponsibilities: [
      "Recruit and onboard new employees with the right skills and qualifications.",
      "Manage HR processes, including performance reviews and employee engagement.",
      "Ensure compliance with employment laws and regulations.",
      "Effectively communicate and resolve employee issues and conflicts.",
    ],
    jobDescription:
      "We are looking for an HR professional to join our team. The ideal candidate will play a key role in recruiting and onboarding new employees with the right skills and qualifications. You will also manage HR processes, including performance reviews and employee engagement, and ensure compliance with employment laws and regulations. Additionally, you will effectively communicate and resolve employee issues and conflicts. Join us to make a positive impact on our organization.",
    company: "HR Solutions Inc.",
    contactEmail: "hr@hrsolutionsinc.com",
    deadline: "2023-12-31",
  },
  {
    jobId: "id10",
    title: "Technical Consultant",
    experience: "3-5 years",
    location: "Bangalore",
    salary: "18-22 lacs",
    skills: ["Consulting", "Technical Expertise", "Problem Solving"],
    rolesAndResponsibilities: [
      "Provide technical consulting services to clients and address their unique needs.",
      "Identify and solve complex technical problems through innovative solutions.",
      "Collaborate with clients to understand their goals and recommend tailored strategies.",
      "Deliver presentations and training sessions to clients as needed.",
    ],
    jobDescription:
      "We are seeking a Technical Consultant to join our team. The ideal candidate will provide technical consulting services to clients and address their unique needs. You will identify and solve complex technical problems through innovative solutions and collaborate with clients to understand their goals and recommend tailored strategies. Additionally, you will deliver presentations and training sessions to clients as needed. Join us to provide valuable technical expertise to our clients.",
    company: "TechConsult Innovations",
    contactEmail: "careers@techconsult.com",
    deadline: "2023-11-25",
  },
  {
    jobId: "id11",
    title: "Front-end Developer",
    experience: "2-4 years",
    location: "Bangalore",
    salary: "14-17 lacs",
    skills: ["JavaScript", "React", "HTML", "CSS", "UI/UX Design"],
    rolesAndResponsibilities: [
      "Develop and maintain front-end components of web applications.",
      "Collaborate with designers to create visually appealing and responsive user interfaces.",
      "Optimize web applications for performance and cross-browser compatibility.",
      "Stay up to date with the latest front-end technologies and trends.",
    ],
    jobDescription:
      "We are looking for a Front-end Developer to join our team. The ideal candidate will be responsible for developing and maintaining front-end components of web applications. You will collaborate with designers to create visually appealing and responsive user interfaces, optimize web applications for performance, and ensure cross-browser compatibility. Additionally, you will stay up to date with the latest front-end technologies and trends. Join us to work on user-friendly web interfaces.",
    company: "FrontEnd Creations",
    contactEmail: "careers@frontendcreations.com",
    deadline: "2023-12-10",
  },
  {
    jobId: "id12",
    title: "Database Administrator",
    experience: "3-5 years",
    location: "Bangalore",
    salary: "16-20 lacs",
    skills: [
      "Database Management",
      "SQL",
      "Performance Tuning",
      "Backup and Recovery",
    ],
    rolesAndResponsibilities: [
      "Manage and administer relational databases, ensuring data integrity and security.",
      "Optimize database performance, including query tuning and indexing.",
      "Implement backup and recovery strategies to protect critical data.",
      "Collaborate with developers to design efficient database schemas.",
    ],
    jobDescription:
      "We are seeking a Database Administrator to join our team. The ideal candidate will manage and administer relational databases, ensuring data integrity and security. You will be responsible for optimizing database performance, including query tuning and indexing, and implementing backup and recovery strategies to protect critical data. Additionally, you will collaborate with developers to design efficient database schemas. Join us to manage and optimize our databases effectively.",
    company: "DBA Solutions",
    contactEmail: "jobs@dbasolutions.com",
    deadline: "2023-11-30",
  },
  {
    jobId: "id13",
    title: "Network Engineer",
    experience: "2-4 years",
    location: "Bangalore",
    salary: "14-17 lacs",
    skills: [
      "Network Configuration",
      "Cisco",
      "Firewall Management",
      "Troubleshooting",
    ],
    rolesAndResponsibilities: [
      "Design, configure, and maintain network infrastructure to ensure reliability.",
      "Monitor network performance and troubleshoot network-related issues.",
      "Implement and manage firewall and security measures to protect the network.",
      "Collaborate with other IT teams to support network requirements.",
    ],
    jobDescription:
      "We are looking for a Network Engineer to join our team. The ideal candidate will design, configure, and maintain network infrastructure to ensure reliability. You will be responsible for monitoring network performance and troubleshooting network-related issues. Additionally, you will implement and manage firewall and security measures to protect the network and collaborate with other IT teams to support network requirements. Join us to ensure the reliability and security of our network infrastructure.",
    company: "Network Solutions Inc.",
    contactEmail: "careers@networksolutionsinc.com",
    deadline: "2023-11-25",
  },
  {
    jobId: "id14",
    title: "UX/UI Designer",
    experience: "2-4 years",
    location: "Bangalore",
    salary: "14-17 lacs",
    skills: [
      "UI/UX Design",
      "Prototyping",
      "User Research",
      "Adobe Creative Suite",
    ],
    rolesAndResponsibilities: [
      "Create user-centric designs for web and mobile applications.",
      "Conduct user research to understand user needs and behaviors.",
      "Develop wireframes, prototypes, and design mockups for product interfaces.",
      "Collaborate with cross-functional teams to iterate and refine designs.",
    ],
    jobDescription:
      "We are seeking a UX/UI Designer to join our design team. The ideal candidate will create user-centric designs for web and mobile applications. You will conduct user research to understand user needs and behaviors and develop wireframes, prototypes, and design mockups for product interfaces. Additionally, you will collaborate with cross-functional teams to iterate and refine designs. Join us to make a significant impact on the user experience of our products.",
    company: "Design Innovators",
    contactEmail: "jobs@designinnovators.com",
    deadline: "2023-12-05",
  },
  {
    jobId: "id15",
    title: "DevOps Engineer",
    experience: "3-5 years",
    location: "Bangalore",
    salary: "16-20 lacs",
    skills: [
      "DevOps Tools",
      "Continuous Integration",
      "Infrastructure as Code",
      "Cloud Services",
    ],
    rolesAndResponsibilities: [
      "Automate and streamline software development and deployment processes.",
      "Implement and manage CI/CD pipelines for efficient code delivery.",
      "Maintain and scale cloud-based infrastructure using IaC practices.",
      "Collaborate with development and IT teams to ensure system reliability and security.",
    ],
    jobDescription:
      "We are looking for a DevOps Engineer to join our team. The ideal candidate will automate and streamline software development and deployment processes. You will implement and manage CI/CD pipelines for efficient code delivery and maintain and scale cloud-based infrastructure using Infrastructure as Code (IaC) practices. Additionally, you will collaborate with development and IT teams to ensure system reliability and security. Join us to optimize and secure our software development and deployment workflows.",
    company: "DevOps Solutions Inc.",
    contactEmail: "careers@devopssolutionsinc.com",
    deadline: "2023-11-30",
  },
  {
    jobId: "id16",
    title: "Data Scientist",
    experience: "3-5 years",
    location: "Bangalore",
    salary: "16-20 lacs",
    skills: ["Data Analysis", "Machine Learning", "Python", "Big Data Tools"],
    rolesAndResponsibilities: [
      "Analyze and interpret complex datasets to extract actionable insights.",
      "Develop and deploy machine learning models for predictive analytics.",
      "Utilize big data tools and frameworks for data processing and analysis.",
      "Collaborate with business stakeholders to drive data-driven decision-making.",
    ],
    jobDescription:
      "We are seeking a Data Scientist to join our data analytics team. The ideal candidate will analyze and interpret complex datasets to extract actionable insights. You will develop and deploy machine learning models for predictive analytics and utilize big data tools and frameworks for data processing and analysis. Additionally, you will collaborate with business stakeholders to drive data-driven decision-making. Join us to uncover valuable insights from data and drive informed decisions.",
    company: "Data Insights Ltd.",
    contactEmail: "jobs@datainsights.com",
    deadline: "2023-11-25",
  },
  {
    jobId: "id17",
    title: "Quality Assurance Engineer",
    experience: "2-4 years",
    location: "Bangalore",
    salary: "14-17 lacs",
    skills: [
      "Test Automation",
      "Manual Testing",
      "Test Plans",
      "Defect Tracking",
    ],
    rolesAndResponsibilities: [
      "Develop and execute test plans and test cases for software products.",
      "Automate test scripts to ensure efficient and comprehensive testing.",
      "Identify and document software defects and work with development teams for resolution.",
      "Collaborate with cross-functional teams to improve product quality and reliability.",
    ],
    jobDescription:
      "We are looking for a Quality Assurance Engineer to join our quality assurance team. The ideal candidate will develop and execute test plans and test cases for software products. You will also automate test scripts to ensure efficient and comprehensive testing and identify and document software defects, working with development teams for resolution. Additionally, you will collaborate with cross-functional teams to improve product quality and reliability. Join us to ensure the quality and reliability of our software products.",
    company: "QualityTech Solutions",
    contactEmail: "careers@qualitytech.com",
    deadline: "2023-12-10",
  },
  {
    jobId: "id18",
    title: "Cybersecurity Analyst",
    experience: "2-4 years",
    location: "Bangalore",
    salary: "14-17 lacs",
    skills: [
      "Security Analysis",
      "Incident Response",
      "Network Security",
      "Security Tools",
    ],
    rolesAndResponsibilities: [
      "Monitor and analyze security threats and vulnerabilities to protect the organization's assets.",
      "Respond to security incidents and conduct root cause analysis.",
      "Implement and manage security tools and measures to secure the network and data.",
      "Collaborate with IT and compliance teams to ensure regulatory compliance.",
    ],
    jobDescription:
      "We are seeking a Cybersecurity Analyst to join our cybersecurity team. The ideal candidate will monitor and analyze security threats and vulnerabilities to protect the organization's assets. You will respond to security incidents and conduct root cause analysis and implement and manage security tools and measures to secure the network and data. Additionally, you will collaborate with IT and compliance teams to ensure regulatory compliance. Join us to safeguard our organization's assets and data.",
    company: "SecureTech Solutions Inc.",
    contactEmail: "jobs@securetechsolutions.com",
    deadline: "2023-11-30",
  },
  {
    jobId: "id19",
    title: "Business Analyst",
    experience: "2-4 years",
    location: "Bangalore",
    salary: "14-17 lacs",
    skills: [
      "Business Analysis",
      "Requirements Gathering",
      "Documentation",
      "Stakeholder Communication",
    ],
    rolesAndResponsibilities: [
      "Gather and document business requirements to drive project objectives.",
      "Analyze data and processes to identify opportunities for business improvement.",
      "Communicate with stakeholders to ensure project alignment with business goals.",
      "Collaborate with cross-functional teams to implement process improvements.",
    ],
    jobDescription:
      "We are looking for a Business Analyst to join our team. The ideal candidate will gather and document business requirements to drive project objectives. You will analyze data and processes to identify opportunities for business improvement and communicate with stakeholders to ensure project alignment with business goals. Additionally, you will collaborate with cross-functional teams to implement process improvements. Join us to drive business improvements and enhance project success.",
    company: "BizTech Innovations",
    contactEmail: "careers@biztechinnovations.com",
    deadline: "2023-11-25",
  },
  {
    jobId: "id20",
    title: "Product Manager",
    experience: "4-6 years",
    location: "Bangalore",
    salary: "20-25 lacs",
    skills: [
      "Product Management",
      "Market Research",
      "Product Strategy",
      "Agile Methodology",
    ],
    rolesAndResponsibilities: [
      "Define and execute product strategy to meet business and customer needs.",
      "Conduct market research and analysis to identify opportunities and trends.",
      "Lead cross-functional teams to deliver high-quality products within an Agile framework.",
      "Collaborate with stakeholders to align product development with business objectives.",
    ],
    jobDescription:
      "We are looking for an experienced Product Manager to lead our product development efforts. The ideal candidate will define and execute product strategy, conduct market research, and lead cross-functional teams to deliver high-quality products. You will work closely with stakeholders to align product development with business objectives. Join us to drive innovation and make a significant impact on our product offerings.",
    company: "Product Innovators",
    contactEmail: "jobs@productinnovators.com",
    deadline: "2023-11-25",
  },
];

export { mockJobsData };
